version: '3.9'
name: 'rinha-backend-micronaut'

services:
  api-1:
    image: joaovertelo/rinha-backend-micronaut:latest
#    restart: on-failure
    build:
      context: .
    hostname: api-1
    environment:
      - SERVER_PORT=8080
      - DATABASE_URL=jdbc:postgresql://db:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      db:
        condition: service_healthy
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: '1.25GB'
    networks:
      - app-network

  api-2:
    image: joaovertelo/rinha-backend-micronaut:latest
    build:
      context: .
    hostname: api-2
    environment:
      - SERVER_PORT=8080
      - DATABASE_URL=jdbc:postgresql://db:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
#      - REDIS_HOST=cache
    depends_on:
      db:
        condition: service_healthy
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: '1.25GB'
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-1
      - api-2
    ports:
      - "9999:9999"
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '0.25GB'

  db:
    image: postgres:latest
    container_name: rinha-backend-db
    hostname: db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s
      resources:
        limits:
          cpus: '0.05'
          memory: '0.5GB'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 3s
      timeout: 5s
      retries: 10
    networks:
      - app-network

networks:
  app-network: